version: "3.9"
services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    restart: always
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - '5672:5672'
      - '15672:15672'
    labels:
      NAME: "rabbitmq"
    volumes:
      - "./etc/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json"

networks:
  notification:
    name: custom_notification
    driver: bridge