version: "3.9"
services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3.11-management-alpine
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - '5672:5672'
      - '15672:15672'

networks:
  notification:
    name: custom_notification
    driver: custom-driver-1